-- data.sql
-- Initial sample data (at least 5 rows per main table)
-- IDs are generated by DBMS (we don't explicitly set id fields).
-- Subsequent inserts reference rows by unique fields (login/name).

-- 1) Users
INSERT INTO users (login, password) VALUES
('alice', 'alicepass'),
('bob',   'bobpass'),
('carol', 'carolpass'),
('dave',  'davepass'),
('nick',  'nickpass'),
('ann',  'annpass'),
('dima',  'dimapass'),
('lena',  'lenepass'),
('tina',  'tinapass'),
('eve',   'evepass');

-- 2) Chatrooms (owner referenced by login)
INSERT INTO chatrooms (name, owner_id) VALUES
('General', (SELECT id FROM users WHERE login = 'alice')),
('Random',  (SELECT id FROM users WHERE login = 'bob')),
('Java',    (SELECT id FROM users WHERE login = 'carol')),
('Music',   (SELECT id FROM users WHERE login = 'alice')),
('Sports',  (SELECT id FROM users WHERE login = 'eve')),
('Beauty',  (SELECT id FROM users WHERE login = 'lena'));

-- 3) Messages (author_id and chatroom_id resolved via subqueries)
INSERT INTO messages (author_id, chatroom_id, text, created_at) VALUES
((SELECT id FROM users WHERE login='alice'), (SELECT id FROM chatrooms WHERE name='General'),
    'Hello everyone!', '2025-09-20 10:00:00'),

((SELECT id FROM users WHERE login='bob'), (SELECT id FROM chatrooms WHERE name='General'),
    'Hi Alice!', '2025-09-20 10:01:00'),

((SELECT id FROM users WHERE login='carol'), (SELECT id FROM chatrooms WHERE name='Java'),
    'Anyone knows Java streams?', '2025-09-21 09:30:00'),

((SELECT id FROM users WHERE login='dave'), (SELECT id FROM chatrooms WHERE name='Music'),
    'Check this new song!', '2025-09-21 12:00:00'),

((SELECT id FROM users WHERE login='alice'), (SELECT id FROM chatrooms WHERE name='Sports'),
    'Who won the match?', '2025-09-22 20:00:00'),

((SELECT id FROM users WHERE login='dima'), (SELECT id FROM chatrooms WHERE name='Java'),
    'Good news!', '2025-09-22 17:21:34'),

((SELECT id FROM users WHERE login='ann'), (SELECT id FROM chatrooms WHERE name='Sports'),
    'Who wins?', '2025-09-22 22:11:26'),

((SELECT id FROM users WHERE login='eve'), (SELECT id FROM chatrooms WHERE name='Sports'),
    'Our team did!', '2025-09-22 20:05:00');

-- 4) Many-to-many participants (users_chatrooms) — at least 5 rows
INSERT INTO users_chatrooms (user_id, chatroom_id) VALUES
((SELECT id FROM users WHERE login='alice'), (SELECT id FROM chatrooms WHERE name='General')),
((SELECT id FROM users WHERE login='bob'),   (SELECT id FROM chatrooms WHERE name='General')),
((SELECT id FROM users WHERE login='carol'), (SELECT id FROM chatrooms WHERE name='General')),
((SELECT id FROM users WHERE login='alice'), (SELECT id FROM chatrooms WHERE name='Music')),
((SELECT id FROM users WHERE login='dave'),  (SELECT id FROM chatrooms WHERE name='Music')),
((SELECT id FROM users WHERE login='carol'), (SELECT id FROM chatrooms WHERE name='Java')),
((SELECT id FROM users WHERE login='bob'),   (SELECT id FROM chatrooms WHERE name='Random')),
((SELECT id FROM users WHERE login='eve'),   (SELECT id FROM chatrooms WHERE name='Sports')),
((SELECT id FROM users WHERE login='nick'),   (SELECT id FROM chatrooms WHERE name='Random')),
((SELECT id FROM users WHERE login='ann'),   (SELECT id FROM chatrooms WHERE name='Sports')),
((SELECT id FROM users WHERE login='ann'),   (SELECT id FROM chatrooms WHERE name='Java')),
((SELECT id FROM users WHERE login='dima'),   (SELECT id FROM chatrooms WHERE name='Java')),
((SELECT id FROM users WHERE login='dima'),   (SELECT id FROM chatrooms WHERE name='Music')),
((SELECT id FROM users WHERE login='alice'), (SELECT id FROM chatrooms WHERE name='Sports'));
